[package]
name = "rust-pgdatadiff"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Rust library for comparing two PostgreSQL databases"
readme = "README.md"
homepage = "https://github.com/pavlospt/rust-pgdatadiff"
repository = "https://github.com/pavlospt/rust-pgdatadiff"
keywords = ["postgres", "postgresql", "diff"]
documentation = "https://docs.rs/rust-pgdatadiff"

[dependencies]
anyhow = "1.0.81"
tokio = { version = "1.37.0", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-native-tls", "postgres"] }
colored = "2.1.0"
futures = { version = "0.3.30", default-features = true, features = ["async-await"] }
env_logger = "0.11.3"
log = "0.4.21"
async-trait = "0.1.79"
pretty_assertions = "1.4.0"
rayon = "1.10.0"

[dependencies.clap]
version = "4.5.4"
features = ["derive"]

[dev-dependencies]
mockall = "0.12.1"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }

[lib]
test = true
edition = "2021"
crate-type = ["lib"]
name = "rust_pgdatadiff"

[workspace]
members = ["rust-pgdatadiff-client"]
