name: Git Checks

on: [pull_request]

jobs:
  block-fixup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Block Fixup Commit Merge
        uses: alexkappa/block-fixup-merge-action@v2
  add-assignee:
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            if (issue.data.assignees.length === 0) {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: [context.actor]
              });
            }
